/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9ff",
        "surface-dim": "#cfdaf2",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dee8ff",
        "surface-container-highest": "#d8e3fb",
        "on-surface": "#111c2d",
        "on-surface-variant": "#414943",
        "inverse-surface": "#263143",
        "inverse-on-surface": "#ecf1ff",
        "outline": "#717972",
        "outline-variant": "#c1c9c1",
        "surface-tint": "#3b674e",
        "primary": "#002c19",
        "on-primary": "#ffffff",
        "primary-container": "#15432c",
        "on-primary-container": "#81b092",
        "inverse-primary": "#a1d2b2",
        "secondary": "#2a6866",
        "on-secondary": "#ffffff",
        "secondary-container": "#aeebe8",
        "on-secondary-container": "#2f6c6a",
        "tertiary": "#002745",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#023d67",
        "on-tertiary-container": "#7ea8d8",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#bdeecd",
        "primary-fixed-dim": "#a1d2b2",
        "on-primary-fixed": "#002111",
        "on-primary-fixed-variant": "#224f37",
        "secondary-fixed": "#b1eeeb",
        "secondary-fixed-dim": "#95d1cf",
        "on-secondary-fixed": "#00201f",
        "on-secondary-fixed-variant": "#084f4e",
        "tertiary-fixed": "#d0e4ff",
        "tertiary-fixed-dim": "#9fcafc",
        "on-tertiary-fixed": "#001d35",
        "on-tertiary-fixed-variant": "#174974",
        "background": "#f9f9ff",
        "on-background": "#111c2d",
        "surface-variant": "#d8e3fb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "gutter-mobile": "1rem",
        "gutter-tablet": "1.5rem",
        "gutter-desktop": "2rem",
        "margin-mobile": "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "container-max": "80rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        heading: ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "code-num": ["Inter", "monospace"]
      },
      fontSize: {
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "code-num": ["15px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
